Repository UsmanAhmadSaeed/Animations, pull requests merged in 2022-10, with the labels that each got.

#44 Added clipping navigation menu
  Menu Animations/Clipping Navigation Menu/css/scss.css
  Menu Animations/Clipping Navigation Menu/css/scss.css.map
  Menu Animations/Clipping Navigation Menu/css/scss.scss
  Menu Animations/Clipping Navigation Menu/index.html
  Menu Animations/Clipping Navigation Menu/js/script.js
  Scroll Animations/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#42 New Card Animation Added
  Card Animations/btn cards/image.jpg
  Card Animations/btn cards/index.html
  Card Animations/btn cards/profile.png
  Card Animations/btn cards/script.js
  Card Animations/btn cards/style.css
  Click Animations/big-button/index.html
  Hover Animations/Flip Animation on Hover/index.html
  Hover Animations/Flip Animation on Hover/style.css
  Landing Page/index.html
  Load Animations/Bouncing Circles/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#46 ring wave animation
  Load Animations/Ring wave animation/index.html
  Load Animations/Ring wave animation/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#51 Added Card Hover Animations Hacktoberfest-2022
  Card_Hover_Animations/index.html
  Card_Hover_Animations/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#57 Fixed lag issues in Cards
  Card Animations/Hover to animate cards/index.html
  Card Animations/Hover to animate cards/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#58 New animation
  Load Animations/Circularly Rotating Boxes/index.html
  Load Animations/Circularly Rotating Boxes/style.css
Labels: Changes pending

#61 Added Outside Curve Navigation Menu
  Menu Animations/Outside Curve Navigation Menu/index.html
  Menu Animations/Outside Curve Navigation Menu/script.js
  Menu Animations/Outside Curve Navigation Menu/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#60 Created loading circles animation
  Load Animations/Loading Circles/index.html
  Load Animations/Loading Circles/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#52 Login Form Animation
  Form Animations/LoginAnimation/index.html
  Form Animations/LoginAnimation/style.css
Labels: Changes pending

#70 Guideline adherence - updated readme
  README.md
Labels: pending approval

#64 Added an RGB hover button animation in the hover animation
  Hover Animations/RGB button animation/index.html
  Hover Animations/RGB button animation/style.css
  README.md
Labels: hacktoberfest-accepted, pending approval

#77 Filtered and improved some animations
  .vscode/settings.json
  Filtering/Flip Animation on Hover/index.html
  Filtering/Flip Animation on Hover/kkritii.jpg
  Filtering/Flip Animation on Hover/style.css
  Filtering/Heartbeat Loader/index.html
  Filtering/Heartbeat Loader/script.js
  Filtering/Heartbeat Loader/style.css
  Filtering/Hover to invert color card/Card 1/card.css
  Filtering/Hover to invert color card/Card 1/card.html
  Filtering/Hover to invert color card/card.css
  Filtering/Hover to invert color card/card.html
  Filtering/Looping Circle/.vscode/settings.json
  Filtering/Looping Circle/index.html
  Filtering/Looping Circle/styles.css
  Filtering/Rainbow Lights/index.html
  Filtering/Rainbow Lights/style.css
  Filtering/Tilting Animation on Hover/glassmorph.css
  Filtering/Tilting Animation on Hover/glassmorph.html
  Filtering/Tilting Animation on Hover/project1.svg
  Filtering/Tilting Animation on Hover/vanilla-tilt.js
  Hover Animations/Glow Icons/style.css
  Load Animations/Ghost Loading Animation/style.css
  README.md
Labels: hacktoberfest-accepted
